stages:
  - build-test
  - benchmark
  - benchmark-completion

before_script:
  - (cd core-lib && git remote add smarr https://github.com/smarr/SOM.git && git fetch --all) || true
  - git submodule update --init

build-and-test-interpreters:
  stage: build-test
  tags: [yuria2]
  script:
    - cargo clean

    - cargo build --release --features=som-gc/marksweep --features=idiomatic
    # - cargo clippy --features=som-gc/marksweep --features=nan
    - lz4 ./target/release/som-interpreter-bc som-interpreter-bc_idiomatic.lz4

    - cargo build --release --features=som-gc/marksweep --features=nan
    - cargo clippy --features=som-gc/marksweep --features=nan
    - lz4 ./target/release/som-interpreter-bc som-interpreter-bc_nan.lz4

    - cargo build --release --features=som-gc/marksweep --features=lbits
    - cargo clippy --features=som-gc/marksweep --features=lbits
    - lz4 ./target/release/som-interpreter-bc som-interpreter-bc_lbits.lz4

    # Package and Upload
    - |
      sftp tmp-artifacts << EOF
        -mkdir incoming/${CI_PIPELINE_ID}/
        put som-interpreter-bc_idiomatic.lz4 incoming/${CI_PIPELINE_ID}/
        put som-interpreter-bc_nan.lz4 incoming/${CI_PIPELINE_ID}/
        put som-interpreter-bc_lbits.lz4 incoming/${CI_PIPELINE_ID}/
      EOF

benchmark:
  parallel:
    matrix:
      - MACHINE:
          - yuria
          - yuria2
          - yuria3
  stage: benchmark
  tags: [$MACHINE]
  script:
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-interpreter-bc_idiomatic.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-interpreter-bc_lbits.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-interpreter-bc_nan.lz4

    - mkdir -p ./target/release
#    - lz4 -d som-interpreter-ast.lz4 ./target/release/som-interpreter-ast
    - lz4 -d som-interpreter-bc_nan.lz4 ./target/release/som-interpreter-bc_nan
    - lz4 -d som-interpreter-bc_lbits.lz4 ./target/release/som-interpreter-bc_lbits
    - lz4 -d som-interpreter-bc_idiomatic.lz4 ./target/release/som-interpreter-bc_idiomatic

    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf #t:$MACHINE

report-completion:
  stage: benchmark-completion
  tags: [yuria2]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
